#!/bin/sh
# FFactor processes factored file into developed files.
# Copyright (C) 2015  ia0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "$(dirname "$0")/common.sh"

A='B C E O V'

for a in $A
do
  eval va=\$$a
  if [ "$va" ]
  then
    [ "$a" = B -o "$a" = C ] ||
    get_$a | grep -F "$va" >/dev/null ||
    echo "\$(error Bad value $a=$va)"
  else
    va=$(get_$a | head -n1)
    [ "$a" = C -a ! "$va" ] &&
    echo "\$(error No compiler found)"
  fi
  echo "$a := $va"
  if eval \$cst_$a
  then
    echo "ifneq (\$($a),$va)"
    echo "\$(error Cannot override $a=$va with $a=\$($a))"
    echo "endif"
  fi
  unset va
done
unset a

sp="\$(info [33m"
for a in $A
do
  echo -n "$sp$a=\$($a)"
  sp=" "
done
unset a
unset sp
echo "[m)"
