#!/bin/sh
# ffactor expands factored files according to an environment.
# Copyright (C) 2015  ia0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "$(dirname "$0")/common.sh"

for a in B C E O V
do
  eval va=\$$a
  if [ "$va" ]
  then
    [ "$a" = B -o "$a" = C ] ||
    get_$a | grep -F "$va" >/dev/null ||
    echo "\$(error Bad value FF_$a=$va)"
  else
    va=$(get_$a | head -n1)
    [ "$a" = C -a ! "$va" ] &&
    echo "\$(error No compiler found)"
  fi
  echo "FF_$a := \$(or \$(FF_$a),$va)"
  if eval \$cst_$a
  then
    echo "ifneq (\$(FF_$a),$va)"
    echo "\$(error Cannot override FF_$a=$va with FF_$a=\$(FF_$a))"
    echo "endif"
  else
    echo "ifeq (\$(filter $(echo $(get_$a)),\$(FF_$a)),)"
    echo "\$(error Bad value FF_$a=\$(FF_$a))"
    echo "endif"
  fi
  unset va
done
unset a
