#!/bin/sh
# ffactor expands factored files according to an environment.
# Copyright (C) 2015  ia0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "$(dirname "$0")/common.sh"

for C in $(get_C)
do
  for E in $(get_E)
  do
    for O in $(get_O)
    do
      for V in $(get_V)
      do
        make clean
        make -j C=$C E=$E O=$O V=$V ff_suite || exit 1
      done
    done
  done
done
make clean
